version: "3.7"
services:
  comment_service:
    container_name: comment_service
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend
      - mongo_network
    depends_on: 
      - mongo
    ports:
      - 4000:3000
    restart: unless-stopped

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    env_file:
      - db.env
    ports: 
      - "27017:27017"
    networks:
      - mongo_network

networks:
  mongo_network:
  backend:
      
# volumes:
